name: LEP
version: ${project.version}
main: org.besser.lep.Lep
api-version: '1.20'
authors: [brandonusa, hexedepixel]
contributors: [League of Nations]
description: LoN Economy Plugin
website: https://github.com/besser435/LEP

commands:
  lep:
    description: The LEP prefix
    #usage: /<command> [args]
    aliases: [l]
    permission: lep.lep
permissions:
  lep.lep:
    description: Permission to use the main LEP command.
    default: true


